# Generated by Django 4.0.4 on 2022-11-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
