# Generated by Django 4.0.4 on 2022-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_event_creator_alter_organizer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
