# Generated by Django 4.0.4 on 2022-11-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_event_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='corg',
        ),
    ]
