# Generated by Django 4.0.4 on 2022-12-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_organizer_alter_event_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='limit',
            new_name='tickets_ava',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_rem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
