# Generated by Django 4.0.4 on 2022-12-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_limit_event_tickets_ava_event_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets_ava',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_rem',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
