# Generated by Django 4.0.4 on 2022-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_event_tickets_ava_alter_event_tickets_rem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets_ava',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_rem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
