# Generated by Django 4.0.4 on 2022-12-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_favourite_bookmark_rename_photo_event_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets_rem',
        ),
    ]
