# Generated by Django 4.0.4 on 2022-12-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tix',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tix_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tix_mail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tix_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
