# Generated by Django 4.0.4 on 2022-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_ticket_tix_ticket_tix_code_ticket_tix_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tix_phone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
