# Generated by Django 4.0.4 on 2022-12-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ticket_tix_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tix_code',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
