# Generated by Django 4.0.4 on 2022-12-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_review_created_ticket_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=0, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
