# Generated by Django 4.0.4 on 2022-12-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=2, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
