# Generated by Django 4.0.4 on 2022-12-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
