# Generated by Django 4.0.4 on 2022-12-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.SlugField(max_length=1000, null=True),
        ),
    ]
