# Generated by Django 4.0.4 on 2022-12-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_event_poster_alter_media_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
