# Generated by Django 4.0.4 on 2022-12-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='poster',
        ),
    ]
