# Generated by Django 4.0.4 on 2023-01-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='photo',
            field=models.FileField(upload_to='media'),
        ),
    ]
