# Generated by Django 4.0.4 on 2023-01-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_media_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='photo',
        ),
        migrations.AddField(
            model_name='media',
            name='photos',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
