# Generated by Django 4.0.4 on 2023-01-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_media_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
