# Generated by Django 4.0.4 on 2023-01-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_event_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='phone2',
        ),
        migrations.AddField(
            model_name='organizer',
            name='account_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='bank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='poster',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
