# Generated by Django 4.0.4 on 2023-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_organizer_phone2_organizer_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='biz_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
