# Generated by Django 4.0.4 on 2023-02-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_organizer_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_ava',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
