# Generated by Django 4.0.4 on 2023-02-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_event_ticket_ava'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_ava',
        ),
    ]
