# Generated by Django 4.0.4 on 2023-02-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_event_ticket_ava'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='event_views', to='core.ipmodel'),
        ),
    ]
