# Generated by Django 4.0.4 on 2023-02-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_ipmodel_event_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='views',
        ),
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
