# Generated by Django 4.0.4 on 2023-02-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_event_views_event_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='event',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
