# Generated by Django 4.1.5 on 2023-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_media_video_remove_organizer_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='bank_code',
            field=models.IntegerField(choices=[('044', '044'), ('023', '023'), ('050', '050'), ('214', '214'), ('070', '070'), ('011', '011'), ('058', '058'), ('030', '030'), ('301', '301'), ('082', '082'), ('526', '526'), ('101', '101'), ('221', '221'), ('076', '076'), ('068', '068'), ('232', '232'), ('100', '100'), ('102', '102'), ('032', '032'), ('033', '033'), ('215', '215'), ('035', '035'), ('057', '057')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'ENtertainment'), ('Tech', 'TEch'), ('Professional', 'PRofessional'), ('Religious', 'REligious')], max_length=50, null=True),
        ),
    ]
