# Generated by Django 4.1.5 on 2023-03-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_organizer_bank_code_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
    ]
