# Generated by Django 4.1.5 on 2023-03-13 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0079_organizer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='bank_code',
            field=models.CharField(choices=[('044', 'Access Bank'), ('023', 'Citibank'), ('050', 'Ecobank'), ('214', 'FCMB'), ('070', 'Fidelity'), ('011', 'First_Bank'), ('058', 'GTB'), ('030', 'Heritage'), ('301', 'Jaiz_Bank'), ('082', 'Keystone'), ('526', 'Parallex'), ('101', 'Providus'), ('221', 'Stanbic'), ('076', 'Skye Bank'), ('068', 'Standard Bank'), ('232', 'Sterling Bank'), ('100', 'Suntrust Bank'), ('102', 'Titan Trust'), ('032', 'Union Bank'), ('033', 'United Bank'), ('215', 'Unity Bank'), ('035', 'Wema Bank'), ('057', 'Zenith Bank')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
